name: flutter_login_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.3.0
  oauth2: ^1.6.0
  oauth2_client: ^1.2.3
  google_fonts: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^2.0.1+1
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.11.1+12
  firebase_core: ^0.4.4
  flutter_rating_bar: ^3.0.1+1
  sqflite:
  path:
  
  shared_preferences: ^0.5.7+3
  flutter_svg: ^0.18.0
  image_picker: ^0.6.7+2
  mime_type: ^0.3.2
  url_launcher: ^5.5.0
  meet_network_image: ^0.1.2
  flutter_cache_manager: ^1.3.0
  flutter_image_compress: ^0.7.0
  octo_image: ^0.2.1
  path_provider: ^1.6.14
  pedantic: ^1.5.0
  sprintf: ^4.1.0
  uuid: ^2.2.2
  optimized_cached_image: ^1.0.0
  firebase_messaging: ^6.0.16
  overlay_support: ^1.0.5
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icons/icono2.png"
 adaptive_icon_background: "assets/icons/icono2.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
   - assets/logos/
   - assets/logos/google.jpg
   - assets/img/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf